
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Customize to your needs...
export PATH=$PATH:"/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin/g4bin:/usr/games"
export PATH=$PATH:$HOME/bin
export PATH="$HOME/.linuxbrew/bin:$HOME/bin:$PATH"

# System variables
export SUBLIME=subl
export VISUAL=$EDITOR
LS_COLORS=$LS_COLORS:'di=0;33:' ; export LS_COLORS

# Set the terminal title
case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;%~\a"}
        ;;
esac

######################
### START OF ALIAS ###
######################
# Push and pop directories on directory stack
alias pu='pushd'
alias po='popd'

# Basic directory operations
alias ...='cd ../..'
alias -- -='cd -'

# Super user
alias _='sudo'
alias please='sudo'

#alias g='grep -in'

# Show history
export HIST_STAMPS="yyyy-mm-dd"
if [ "$HIST_STAMPS" = "mm/dd/yyyy" ]
then
    alias history='fc -fl 1'
elif [ "$HIST_STAMPS" = "dd.mm.yyyy" ]
then
    alias history='fc -El 1'
elif [ "$HIST_STAMPS" = "yyyy-mm-dd" ]
then
    alias history='fc -il 1'
else
    alias history='fc -l 1'
fi

HISTFILE=$HOME/.zsh_history

# List direcory contents
alias lsa='ls -lah'
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -lAh'

# Git
alias g='git'

# Others
alias afind='ack-grep -il'
alias df='df -H'
alias play=mplayer
alias o=xdg-open
alias rm="rm -i"
alias top="top -o %MEM"
alias free="free -gh"
alias h='history | grep -i'
####### END OF ALIAS ######

# Set clobber to overwrite files
setopt clobber
# no globbing
setopt NO_NOMATCH

# LLVM, namely 'clangd'
export PATH="/usr/local/opt/llvm/bin:$PATH"

# virtualenvwrapper
export WORKON_HOME=~/Envs
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /usr/local/bin/virtualenvwrapper.sh
